import { globalColors, globalSizes } from "@/src/theme";
import { StyleSheet } from "react-native";

const shadowOpacity = 0.3;
const shadowRadius = 5;
const elevation = 4;

const cardRadius = 20;

export const cardStyle = StyleSheet.create({
  cardContainer: {
    width: 190,
    height: 250,
    borderRadius: cardRadius,
    backgroundColor: globalColors.whiteColor,
    padding: globalSizes.medium,
    paddingBottom: globalSizes.large,
    marginRight: globalSizes.medium,
    shadowColor: globalColors.headerColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: shadowOpacity,
    shadowRadius: shadowRadius,
    elevation: elevation,
  },
  cardImage: {
    width: "100%",
    height: 100,
    borderRadius: globalSizes.borderRadius,
    marginBottom: globalSizes.small,
    backgroundColor: globalColors.whiteColor,
    borderWidth: 1,
    borderColor: globalColors.primaryMutedColor,
  },
  cardTitle: {
    fontSize: globalSizes.medium,
    fontWeight: 600,
    color: globalColors.headerColor,
  },
  cardParagraph: {
    fontSize: globalSizes.small,
    color: globalColors.textColor,
  },
  cardCategory: {
    fontSize: globalSizes.small,
    color: globalColors.secondaryColor,
    backgroundColor: globalColors.secondaryMutedColor,
    alignSelf: "flex-start",
    paddingHorizontal: globalSizes.xsmall,
    paddingVertical: globalSizes.xsmall / 2,
    borderRadius: globalSizes.xsmall,
    marginBottom: globalSizes.xsmall,
    marginTop: globalSizes.xsmall / 2,
  },
  SelectableCard: {
    width: 150,
    height: 180,
    borderRadius: cardRadius,
    borderColor: "transparent",
    borderWidth: 3,
    backgroundColor: globalColors.whiteColor,
    padding: globalSizes.medium,
    paddingBottom: globalSizes.large,
    marginRight: globalSizes.medium,
    shadowColor: globalColors.headerColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: shadowOpacity,
    shadowRadius: shadowRadius,
    elevation: elevation,
  },
  selectedIndicator: {
    position: "absolute",
    top: -globalSizes.small,
    right: -globalSizes.small,
    width: globalSizes.large,
    height: globalSizes.large,
    borderRadius: 12,
    backgroundColor: globalColors.primaryColor,
    borderWidth: 2,
    borderColor: globalColors.whiteColor,
  },
  SelectableCheckMark: {
    color: globalColors.whiteColor,
    marginLeft: 6,
  },
  AccountCardContainer: {
    width: "100%",
    height: 100,
    borderRadius: globalSizes.borderRadius,
    backgroundColor: globalColors.whiteColor,
    marginBottom: globalSizes.xlarge,
    padding: globalSizes.medium,
    marginRight: globalSizes.medium,
    shadowColor: globalColors.headerColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: shadowOpacity,
    shadowRadius: shadowRadius,
    elevation: elevation,
    flexDirection: "row",
    alignItems: "center",
  },
  AccountCardImage: {
    width: 65,
    height: 65,
    borderRadius: "50%",
    backgroundColor: globalColors.primaryMutedColor,
  },
  AccountTextContainer: {
    marginLeft: globalSizes.medium,
  },
  AccountName: {
    fontSize: globalSizes.medium,
    fontWeight: 600,
    color: globalColors.headerColor,
  },
  AccountType: {
    fontSize: globalSizes.small,
    color: globalColors.textColor,
  },
  SavedRecipeCardContainer: {
    width: "100%",
    height: 350,
    borderRadius: globalSizes.borderRadius,
    backgroundColor: globalColors.whiteColor,
    padding: globalSizes.medium,
    paddingBottom: globalSizes.large,
    marginBottom: globalSizes.medium,
    marginRight: globalSizes.medium,
    shadowColor: globalColors.headerColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: shadowOpacity,
    shadowRadius: shadowRadius,
    elevation: elevation,
  },
  matchBadge: {
    position: "absolute" as const,
    top: 8,
    right: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  matchBadgeText: {
    fontSize: 11,
    fontWeight: "700" as const,
    color: globalColors.whiteColor,
  },
  SavedRecipeCardImage: {
    width: "100%",
    height: 220,
    borderRadius: globalSizes.borderRadius,
    marginBottom: globalSizes.small,
    backgroundColor: globalColors.primaryMutedColor,
    borderWidth: 1,
    borderColor: globalColors.primaryMutedColor,
  },
});
